heat_template_version: 2013-05-23

description: >
  Created 1/28/19 by ucdpadmin.


parameters:
  referenced-image-name:
    type: string
    description: 'Generated'
    label: Referenced Image Name
    default: 'Referenced Image'
  referenced-image-id:
    type: string
    description: 'Generated'
  flavor:
    type: string
    description: 'Flavor to be used for compute instance'
  key_name:
    type: string
    description: 'For most clouds, the name of the key-pair to be used for the compute instance; for VMware clouds, the contents of the public SSH key for the compute instance'
  availability_zone:
    type: string
    description: 'Name of availability zone in which to create the instance'
parameter_groups:
    - { label: 'Image Parameters', parameters: [flavor, key_name, referenced-image-id, referenced-image-name] }
    - { label: 'Network Parameters', parameters: [availability_zone] }
resources:
  referenced-image:
    type: OS::Nova::Server
    properties:
      name: { get_param: referenced-image-name }
      image: { get_param: referenced-image-id }
      flavor: { get_param: flavor } 
      key_name: { get_param: key_name } # Name of key-pair to be used for compute instance
      availability_zone: { get_param: availability_zone }
      metadata: 
        __os_type__ : "Linux"


outputs:
  blueprint_url:
    description: Blueprint Origin URL
    value:  https://marcosbv-ubuntu-server:8445/landscaper/view/projects?open=ucdpadmin_00000000_0000_0000_0000_000000000002-OrionContent/Blueprints/teste1.yaml.yml

