heat_template_version: 2013-05-23

description: >
  Created 1/28/19 by ucdpadmin.

parameters:
  Aplicacao1-componentes_in_Blueprints--ucd_proxy_port:
    type: string
    description: 'The UCD proxy port, the default value is 20080'
    default: '20080'
  ucd_password:
    type: string
    description: 'The user credential for the UrbanCode Deploy server.'
    hidden: true
  ucd_relay_url:
    default: None
    type: string
    description: 'The server URL for an agent relay - leave as ''None'' to enable agents to communicate with server directly.'
  ucd_server_url:
    type: string
    description: 'The server URL for agent communication to UrbanCode Deploy. Do *not* add a trailing slash.'
    default: 'https://marcosbv-ubuntu-server:8443'
  ucd_user:
    type: string
    description: 'The user credential for the UrbanCode Deploy server.'
    default: 'admin'
  referenced-image-name:
    type: string
    description: 'Generated'
    label: Referenced Image Name
    default: 'Referenced Image'
  referenced-image-id:
    type: string
    description: 'Generated'
  flavor:
    type: string
    description: 'Flavor to be used for compute instance'
  key_name:
    type: string
    description: 'For most clouds, the name of the key-pair to be used for the compute instance; for VMware clouds, the contents of the public SSH key for the compute instance'
  availability_zone:
    type: string
    description: 'Name of availability zone in which to create the instance'
  ucd_proxy_port:
    type: string
    description: 'The UCD proxy port, the default value is 20080.'
    default: '20080'
parameter_groups:
    - { label: 'Agent Parameters', parameters: [Aplicacao1-componentes_in_Blueprints--ucd_proxy_port, ucd_password, ucd_proxy_port, ucd_relay_url, ucd_server_url, ucd_user] }
    - { label: 'Image Parameters', parameters: [flavor, key_name, referenced-image-id, referenced-image-name] }
    - { label: 'Network Parameters', parameters: [availability_zone] }
resources:
  Aplicacao1-componentes_in_Blueprints:
    type: Aplicacao1-componentes.yaml
    properties:
      ansible-playbooks_export: { get_resource: referenced-image }
      ucd_proxy_port: { get_param: Aplicacao1-componentes_in_Blueprints--ucd_proxy_port }
      application_name: { get_attr: [ resource_tree, application_name ] }
      environment_name: { get_attr: [ resource_tree, environment_name ] }
      ucd_password: { get_param: ucd_password }
      ucd_relay_url: { get_param: ucd_relay_url }
      ucd_server_url: { get_param: ucd_server_url }
      ucd_user: { get_param: ucd_user }

  referenced-image:
    type: OS::Nova::Server
    properties:
      user_data: { get_resource: referenced-image_mime }
      user_data_format: RAW
      name: { get_param: referenced-image-name }
      image: { get_param: referenced-image-id }
      flavor: { get_param: flavor } 
      key_name: { get_param: key_name } # Name of key-pair to be used for compute instance
      availability_zone: { get_param: availability_zone }
      metadata: 
        __os_type__ : "Linux"

  referenced-image_mime:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: { get_resource: ucd_agent_install_linux }
          subtype: "x-shellscript"


  resource_tree:
    type: IBM::UrbanCode::ResourceTree
    properties:
       urbancode_deploy_url: { get_param: ucd_server_url }
       username: { get_param: ucd_user }
       password: { get_param: ucd_password }
       ucd_relay_url: { get_param: ucd_relay_url }
       ucd_proxy_port: { get_param: ucd_proxy_port }
       team_mappings: 
       application: AppTeste
       base_resource_group: 

  ucd_agent_install_linux:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/usr/bin/env bash
            #ifconfig eth0 mtu 1454 ## Optionally patch the MTU
            export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/root/bin
            arch=`uname -ms | awk '{print tolower($0)}' | tr " " "-" `
            agent_archive=ibm-ucd-agent-$arch.tgz
            if [ "_ucd_relay_url_" != "None" ]; then
              proxy_args="--proxy _ucd_relay_url_:_ucd_proxy_port_"
              ucd_remote_host=_ucd_relay_url_
              agent_args="-r -d -l _ucd_proxy_port_"
              ucd_jms_port=7916
            else
              proxy_args=
              agent_args=
              ucd_remote_host=_ucd_server_url_
              ucd_jms_port=7918
            fi
            if ps -ef | grep -v grep | grep -q air-monitor.jar ; then
              exit 0
            elif [ -d /opt/ibm-ucd ]; then
              exit 0
            fi
            if command -V apt-get && ! command -V curl; then apt-get -y install curl; fi
            if command -V yum && ! command -V curl; then yum -y install curl; fi
            if command -V zypper && ! command -V curl; then zypper -n install curl; fi
            curl $proxy_args -Lk --retry 10 --retry-delay 10 --retry-max-time 120 -o /tmp/$agent_archive -u _ucd_user_:_ucd_password_ "_ucd_server_url_/cli/version/downloadArtifacts?component=ucd-agent-$arch&version=_agent_version_&singleFilePath=$agent_archive"
            tar xfz /tmp/$agent_archive -C /tmp
            /tmp/ibm-ucd-agent-install/install-agent-with-options.sh -t "_agent_team_" -p $ucd_jms_port -s $ucd_remote_host $agent_args -x start -v -n _agent_name_
          params:
            _agent_name_:
               str_replace:
                  template: |
                    "_application_name_._environment_name_"
                  params:
                    _application_name_: { get_attr: [resource_tree, application_name ] }
                    _environment_name_: { get_param: "OS::stack_name" }
            _ucd_server_url_: { get_param: ucd_server_url }
            _ucd_relay_url_: { get_param: ucd_relay_url }
            _ucd_proxy_port_: { get_param: ucd_proxy_port }
            _ucd_user_ : { get_param: ucd_user }
            _ucd_password_ : { get_param: ucd_password }
            _agent_version_ : "7.1"
            _agent_team_ : ""

outputs:
  blueprint_url:
    description: Blueprint Origin URL
    value:  https://marcosbv-ubuntu-server:8445/landscaper/view/projects?open=ucdpadmin_00000000_0000_0000_0000_000000000002-OrionContent/Blueprints/Aplicacao1/Aplicacao1-blueprint.yaml.yml

